name: automerge
on:
  pull_request:
    types:
      - opened
    # Protected branches are available to Pro, Team, and Enterprise users
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
  check_suite:
    types:
      - completed
  status: {}
jobs:
  call-automerge:
    uses: jeremiasrg/workflows/.github/workflows/AutoMergeReleases.yaml@v0.0.16
    secrets:
      token: ${{secrets.TOKEN}}