name: automerge
on:
  pull_request:
    types:
      - opened
  check_suite:
    types:
      - completed
  status: {}
jobs:
  call-automerge:
    uses: ./ReusableAutoMerge.yaml@master
    secrets:
      token: ${{secrets.TOKEN}}