name: Auto Merge Releases
on:
  pull_request:
    types:
      - opened
      - unlabeled
  check_suite:
    types:
      - completed
  status: {}
jobs:
  call-automerge:
    uses: ./.github/workflows/ReusableAutoMerge.yaml
    secrets:
      token: ${{secrets.TOKEN}}