name: automerge
on:
  pull_request:
    types:
      - opened
    # Protected branches are available to Pro, Team, and Enterprise users
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
  check_suite:
    types:
      - completed
  status: {}
jobs:
  # automerge:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: automerge
  #       name: automerge
  #       uses: "pascalgn/automerge-action@v0.15.3"
  #       env:
  #         GITHUB_TOKEN: "${{ secrets.TOKEN }}"
  #         MERGE_LABELS: "Automatic-PR,Release-Type,!work in progress"
  #     - name: Merge result
  #       if: steps.automerge.outputs.mergeResult == "merge_failed"
  #       run: echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} failed!"
          # Posibilities
          # Open Github Issue
          # Send email
          # Send Teams Message or other
  call-automerge:
    uses: jeremiasrg/workflows/.github/workflows/GradleBasic.yaml@v0.0.5
    secrets:
      token: ${{secrets.TOKEN}}
      