name: Run Tests
on: 
  pull_request:
    branches:
      - master
jobs:
  call-gradle-basic:
    uses: jeremiasrg/workflows/.github/workflows/AutoMergeReleases.yaml@v0.0.17
    secrets:
      token: ${{secrets.TOKEN}}