name: Run Tests
on: 
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build