name: Run Tests
on: 
  pull_request:
    branches:
      - master
jobs:
  call-gradle-basic:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: 'Checkout repository'
    #     uses: actions/checkout@v3
    #   - name: gradle build
    #     uses: gradle/gradle-build-action@v2
    #   - name: Execute Gradle build
    #     run: ./gradlew build
    uses: jeremiasrg/workflows/.github/workflows/AutoMergeReleases.yaml@v0.0.5
    secrets:
      token: ${{secrets.TOKEN}}