name: Run Tests
on: 
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: gradlew permission
        run: chmod +x ./gradlew
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: gradle build
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build