name: Run Tests
on: 
  push:
    branches:
      - 'realease/*'
jobs:
  get-branches-to-propagate:
    runs-on: ubuntu-latest
    steps:
      - name: get branches to propagate
      - uses: actions/checkout@v2
      - run: |
          ./branchToPropagate.sh ${{ github.ref_name }}
        shell: bash