name: On Release Commit
on: 
  push:
    branches:
      - 'release/*'
jobs:
  call-on-release-commit:
    uses: jeremiasrg/workflows/.github/workflows/OnReleaseCommit.yaml@v0.0.16
    with:
      branch: ${{github.ref_name}}
    secrets:
      token: ${{secrets.TOKEN}}
  call-automerge:
    needs: call-on-release-commit
    uses: jeremiasrg/workflows/.github/workflows/GradleBasic.yaml@v0.0.16
    secrets:
      token: ${{secrets.TOKEN}}