name: On Release Commit
on: 
  push:
    branches:
      - 'release/*'
jobs:
  get-branches-to-propagate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Script permission
        run: chmod +x ./scripts/branchToPropagate.sh
      - name: get branches to propagate
        run: ./scripts/branchToPropagate.sh ${{ github.ref_name }}
        id: get-branches
      - name: Show branches to merge
        run: echo "The branches to merge  ${{ steps.get-branches.outputs.BRANCHES_TO_MERGE }}"