name: On Release Commit
on: 
  push:
    branches:
      - 'release/*'
jobs:
  call-on-release-commit:
    uses: ./ReusableGetBranchesToPropagate.yaml@master
    with:
      branch: ${{github.ref_name}}
    secrets:
      token: ${{secrets.TOKEN}}