name: On Release Commit
on: 
  push:
    branches:
      - 'realease/*'
jobs:
  get-branches-to-propagate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: get branches to propagate
        run: ./branchToPropagate.sh ${{ github.ref_name }}