name: On Release Commit
on: 
  push:
    branches:
      - 'release/*'
jobs:
  get-branches-to-propagate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Script permission
        run: chmod +x ./scripts/branchToPropagate.sh
      - name: get branches to propagate
        run: ./scripts/branchToPropagate.sh ${{ github.ref_name }}
        id: get-branches
      - name: Show branches to merge
        run: echo "The branches to merge  ${{ steps.get-branches.outputs.BRANCHES_TO_MERGE_STR }}"
      - name: Show branches to merge 2
        run: echo "The branches to merge  ${{ fromJson(steps.get-branches.outputs.BRANCHES_TO_MERGE_MTX) }}"
    outputs:
      branches-to-merge-str: ${{ steps.get-branches.outputs.BRANCHES_TO_MERGE_STR }}"
  propagate:
    needs: get-branches-to-propagate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        propagate-on: ${{ fromJson(needs.get-branches-to-propagate.outputs.branches-to-merge-str) }}
    steps:
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Automatic propagate bug fix
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ matrix.propagate-on }}
          delete-branch: false
          title: 'Automatic propagate bug fix'
          body: |
            Automatic propagate bug fix
          labels: |
            automatic PR
          assignees: jeremiasrg
          reviewers: jeremiasrg
          draft: false

